Header
Max-Loktionov/petly-project-fe pull request #4
Opened 2022-11-10 18:23 UTC by yulyaolshanska

1. Components
2. Styles
3. Icons

2022-11-10 22:12 UTC, Annka-Sarviro approved these changes

2022-11-11 08:50 UTC, Max-Loktionov commented on .eslintrc.json
> +{
цей файл треба видалити повністю

2022-11-11 08:54 UTC, Max-Loktionov requested changes
А svg потрібні?

2022-11-11 14:08 UTC, yulyaolshanska commented on .eslintrc.json
> +{
видалила

2022-11-11 17:53 UTC, Max-Loktionov approved these changes

2022-11-11 17:53 UTC, merged